baseURL = 'https://agnesk92.github.io/'
# languageCode = 'en-us'
title = 'Állatrendőrség Alapítvány'

theme = "ananke"

DefaultContentLanguage = "hu"
SectionPagesMenu = "main"
Paginate = 1 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
site_logo = "images/logo-200.png"
recent_posts_number = 1
background_color_class = "bg-black"
description = "asd Charity Organization"

[[params.ananke_socials]]
name = "facebook"
label = "Facebook"
url = "https://www.facebook.com/allatrendorseg2013"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/allatrendorseg_alapitvany"

[[params.ananke_socials]]
name = "tiktok"
url = "https://www.tiktok.com/@allatrendorsegalapitvany"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@allatrendorsegalapitvany2841"


[languages]

[languages.EN]
title = "Animal Police Organization"
weight = 1
contentDir = "content/en"

[languages.HU]
title = "Állatrendőrség Alapítvány"
weight = 2
contentDir = "content/hu"
